version: '3.8'

services:
  pdf-tag-extraction:
    build: 
      context: .
      dockerfile: Dockerfile
    # Only expose to NPM network, not to host
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      # Memory optimization for t3.micro
      - PYTHONMALLOC=malloc
      - MALLOC_ARENA_MAX=2
      - MALLOC_MMAP_THRESHOLD_=131072
      - MALLOC_TRIM_THRESHOLD_=131072
      - MALLOC_TOP_PAD_=131072
      - MALLOC_MMAP_MAX_=65536
    env_file:
      - .env
    volumes:
      # Use named volumes for better performance on AWS
      - upload_data:/tmp/uploads
      - log_data:/tmp/logs
    restart: unless-stopped
    
    # Strict resource limits for t3.micro (1 vCPU, 1GB RAM)
    deploy:
      resources:
        limits:
          memory: 800M    # Leave 200MB for system
          cpus: '0.8'     # Leave 20% for system processes
        reservations:
          memory: 400M    # Minimum guaranteed memory
          cpus: '0.4'     # Minimum guaranteed CPU
    # Logging optimization to prevent disk space issues
    logging:
      driver: "json-file"
      options:
        max-size: "5m"    # Smaller log files
        max-file: "2"     # Fewer log files
        compress: "true"  # Compress old logs
    
    # Security and performance optimizations
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /var/tmp:noexec,nosuid,size=50m

# Define named volumes for better AWS EBS performance
volumes:
  upload_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./tmp/uploads
  log_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./tmp/logs