version: '3.8'

services:
  pdf-tag-extraction:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    volumes:
      # Mount volume for persistent logs and temporary files
      - ./tmp:/tmp/uploads
      - ./logs:/tmp/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "health_check.py"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 4G  # Increased memory limit
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    # Prevent container from restarting too quickly if it crashes
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"